.PHONY: jg clean

jg:
	jg $(AXI_LITE_LED_PATH)/formal/tc/axi_led_formal_tc.tcl

clean:
	rm -rf jgproject

help:
	@echo "Available targets:"
	@echo "  jg     - Start Jasper FPV"
	@echo "  clean  - Remvoe simulation artefacts"
